### ISSUE TITLE
Git clone fails upon running gatsby new command

### ISSUE THREAD

**Issue by ghost** [lgcolella/gatsby-starter-developer-blog#20]
Running the following...
❯❯ gatsby new my-gatsby-project https://github.com/lgcolella/gatsby-starter-developer-blog

Creates this error I'm assuming it's something wrong with something hosted on npm?

Receiving objects: 100% (255/255), 8.87 MiB | 9.68 MiB/s, done.
success Created starter directory layout
info Installing packages...

npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/@pmmmwh%2freact-refresh-webpack-plugin reason: Unexpected end of JSON input

npm ERR! A complete log of this run can be found in:

 ERROR

Command failed with exit code 1: npm install

  Error: Command failed with exit code 1: npm install

  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

  - init-starter.js:135 install
    [lib]/[gatsby-cli]/lib/init-starter.js:135:7

  - init-starter.js:202 clone
    [lib]/[gatsby-cli]/lib/init-starter.js:202:3

  - init-starter.js:343 initStarter
    [lib]/[gatsby-cli]/lib/init-starter.js:343:5

  - create-cli.js:485
    [lib]/[gatsby-cli]/lib/create-cli.js:485:9

**Comment by ghost** [comment]
After looking into the logs I pulled this from it:
5021 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...nwsFcBAEBCAAQBQJfHyI7'
5021 verbose stack     at JSON.parse (<anonymous>)
5021 verbose stack     at parseJson (/Users/joshleong/.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
5021 verbose stack     at /Users/joshleong/.nvm/versions/node/v14.15.3/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
5021 verbose stack     at runMicrotasks (<anonymous>)
5021 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
5022 verbose cwd /Users/joshleong/Desktop/projects/gatsby/gatsby-starter-developer-blog
5023 verbose Darwin 19.6.0
5024 verbose argv "/Users/joshleong/.nvm/versions/node/v14.15.3/bin/node" "/Users/joshleong/.nvm/versions/node/v14.15.3/bin/npm" "install"
5025 verbose node v14.15.3
5026 verbose npm  v6.14.9
5027 error Unexpected end of JSON input while parsing near '...nwsFcBAEBCAAQBQJfHyI7'
5028 verbose exit [ 1, true ]




I'm assuming the issue has to do with this package:
"gitHead": "a3725370a8b590b7d5a00edc97dd376c90d33159",
      "_id": "@pmmmwh/react-refresh-webpack-plugin@0.4.0",
      "_nodeVersion": "14.4.0",
      "_npmVersion": "6.14.7",
      "dist": {
        "integrity": "sha512-G1xkdDehUdnIk2SBxb6SvEj0/m9gK14ng9O9fBxTKqzs+zTi9dcLwH92fc8AwcqyNXsjHzYC2xqmkjkpe/kOgw==",
        "shasum": "10ebc4cafec2721cbcfafb496aeb1e017f857468",
        "tarball": "https://registry.npmjs.org/@pmmmwh/react-refresh-webpack-plugin/-/react-refresh-webpack-plugin-0.4.0.tgz",
        "fileCount": 48,
        "unpackedSize": 105658,
        "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.4\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJfHyI7CRA9TVsSAnZWagAAXoIP/2gdcCwdJloeaqUxHgbQ\n7O9hQtFKZUQ6uMjxJuqbQAxyQ3dQ+ZuL0q8AW/AmmsRc9e1t09kPm0saa7+g\nt0u2Z44CobuuSfRKHKFhfc1E8ubiajbFUPZkWajwPose6O1MMp7PszS5m6Tu\nqkT3ul8Qb7GPskIiTNpcYbFAZi4pOW3VSd2IgbW6TTCNvmscoNTUIl4Og895\ncNgj8WAI7EQgVcCwrpDpCBwrjvkGGggXQnszp/TUGNDS0Dg5k8vd0LvwFn15\nhMN1mJQc/ODjtEX6JHAWPaAl8DJbMvCYoTSoRgLShVZ4agUp0XZQPw4XxomK\nm5LeOBjpOc8mZh3Z5hjE8xDnPHI3DXQArHrYpaIFb5QNFKwBi67+lh1Ale0s\nflc5vsxPSe5GslH4TmilrX1KFIaGWD0BPsADwKp6hMQm8n2RrCyb5gDdoxSO\nXb4pnFwUOpEFqA8ZO3q0gxJUnyqoIbrmsEzwd1RHB7IqJwFdIoHUrekZKtJ/\nl+ks4C/9XgHOWgmAFhzXU94UhEWCIvlvMbDoOoMHwwrB3CHaMpDV45u2BMoW\nBkuAiZURzQB6zHdJwOxdLnCBwGIYN/oVI6IgUWRIpTXL5iJ8xVoQT6M7GKXJ\nqClaBPVvK90/UtdV7S/iw5J3TTSPq1Ptx5o2PmuL1cUWTQZ8K++w/iYmiWf0\nJfcS\r\n=Yv4O\r\n-----END PGP SIGNATURE-----\r\n"
      },

**Comment by luigi-colella** [comment]
Hi @leodotng,

thank you for reporting this issue. Unfortunately I'm not able to replicate this issue then let me know if you find new insights about it.
